server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    username: root
    password: Bir@tn@g@r1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
    hibernate:
      #create, create-drop, update, none
      ddl-auto: update

    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false